language: go

go:
  - 1.8.x
  - master

env:
  - PATH=$GOPATH/bin:$PATH

install:
  - go get -t ./...
  - go get -u gopkg.in/alecthomas/gometalinter.v1
  - gometalinter.v1 --install
  - go build -i

script:
  - gometalinter.v1 -e "Subprocess launching with variable" -e "cyclomatic complexity" ./...
  - go test -v ./...
